CREATE ROLE master WITH LOGIN PASSWORD 'master' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE TABLESPACE restaurants_tbs OWNER master LOCATION '/var/lib/postgresql/restaurants_tbs';
CREATE DATABASE "Restaurants" WITH OWNER = master ENCODING = 'UTF8' TABLESPACE = restaurants_tbs CONNECTION LIMIT = -1;
\c "Restaurants"
CREATE SCHEMA IF NOT EXISTS main AUTHORIZATION master;
