// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestoRate.Restaurant.Infrastructure.Data;

#nullable disable

namespace RestoRate.Restaurant.Infrastructure.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20251213172213_tags")]
    partial class tags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RestaurantStatus")
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_status");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.RestaurantCuisineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CuisineType")
                        .HasColumnType("integer")
                        .HasColumnName("cuisine_type");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_cuisinetype");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_restaurant_cuisinetype_restaurant_id");

                    b.ToTable("restaurant_cuisinetype", (string)null);
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.RestaurantImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alt_text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_images");

                    b.HasIndex("RestaurantId", "IsPrimary")
                        .HasDatabaseName("ix_restaurant_images_restaurant_id_is_primary");

                    b.ToTable("restaurant_images", (string)null);
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.RestaurantTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_restaurant_tags_tag_id");

                    b.HasIndex("RestaurantId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurant_tags_restaurant_id_tag_id");

                    b.ToTable("restaurant_tags", (string)null);
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.TagAggregate.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_normalized_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.Restaurant", b =>
                {
                    b.OwnsOne("RestoRate.SharedKernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_full_address");

                            b1.Property<string>("House")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_house");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.OwnsOne("RestoRate.SharedKernel.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_address");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.OwnsOne("RestoRate.SharedKernel.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("location_longitude");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.OwnsOne("RestoRate.SharedKernel.ValueObjects.Money", "AverageCheck", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("average_check_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("average_check_currency");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.OwnsOne("RestoRate.SharedKernel.ValueObjects.OpenHours", "OpenHours", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeOnly>("CloseTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("open_hours_close_time");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("open_hours_day_of_week");

                            b1.Property<bool>("IsClosed")
                                .HasColumnType("boolean")
                                .HasColumnName("open_hours_is_closed");

                            b1.Property<TimeOnly>("OpenTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("open_hours_open_time");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.OwnsOne("RestoRate.SharedKernel.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Extension")
                                .HasColumnType("text")
                                .HasColumnName("phone_number_extension");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number_number");

                            b1.Property<string>("OperatorCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_number_operator_code");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("AverageCheck")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("OpenHours")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.RestaurantCuisineType", b =>
                {
                    b.HasOne("RestoRate.Restaurant.Domain.RestaurantAggregate.Restaurant", null)
                        .WithMany("CuisineTypes")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_cuisinetype_restaurants_restaurant_id");
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.RestaurantImage", b =>
                {
                    b.HasOne("RestoRate.Restaurant.Domain.RestaurantAggregate.Restaurant", null)
                        .WithMany("Images")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_images_restaurants_restaurant_id");
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.RestaurantTag", b =>
                {
                    b.HasOne("RestoRate.Restaurant.Domain.RestaurantAggregate.Restaurant", null)
                        .WithMany("Tags")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_tags_restaurants_restaurant_id");

                    b.HasOne("RestoRate.Restaurant.Domain.TagAggregate.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_tags_tag_tag_id");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RestoRate.Restaurant.Domain.RestaurantAggregate.Restaurant", b =>
                {
                    b.Navigation("CuisineTypes");

                    b.Navigation("Images");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
